#include <algorithm>
#include <chrono>
#include <cmath>
#include <mutex>
#include <random>
#include <string>
#include <thread>
#include <utility>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "geometry_msgs/msg/pose_stamped.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "visualization_msgs/msg/marker.hpp"

// Ignition Fortress gz-transport for entity management
#include <ignition/transport/Node.hh>
#include <ignition/msgs/pose.pb.h>
#include <ignition/msgs/boolean.pb.h>
#include <ignition/msgs/entity.pb.h>
#include <ignition/msgs/entity_factory.pb.h>

#include "tb3_rl_bridge/srv/reset_episode.hpp"

using ResetEpisode = tb3_rl_bridge::srv::ResetEpisode;
using namespace std::chrono_literals;

// Auto-generated by tools/gen_positions.py.
// 100 positions, all safe across stages 1-5 (no overlap with inner walls,
// static cylinders at (±1, ±1), or moving-cylinder base positions).
// Both spawn and goal are sampled uniformly from this list each episode.
static const std::vector<std::pair<float, float>> VALID_POSITIONS = {
    {   0.50f,  -1.70f }, {   0.55f,   0.15f }, {   1.65f,  -0.60f },
    {  -0.45f,   0.20f }, {   0.50f,  -0.50f }, {  -0.45f,  -1.05f },
    {   0.55f,   0.40f }, {   0.20f,   0.65f }, {  -1.00f,  -1.70f },
    {   0.20f,  -0.85f }, {   1.70f,   1.30f }, {  -1.75f,   0.80f },
    {   0.00f,  -1.15f }, {   0.40f,  -1.25f }, {   0.95f,   0.15f },
    {  -1.80f,  -0.65f }, {  -0.10f,   0.20f }, {  -0.30f,  -1.05f },
    {   0.15f,   0.85f }, {  -0.20f,   0.05f }, {  -0.60f,   0.30f },
    {  -0.10f,   1.00f }, {  -0.30f,  -0.10f }, {  -0.35f,  -0.60f },
    {  -0.30f,  -0.80f }, {   0.20f,  -1.60f }, {  -0.15f,  -0.30f },
    {   0.35f,   0.45f }, {  -0.30f,   0.30f }, {   0.60f,   1.60f },
    {  -1.80f,   1.00f }, {  -1.55f,   1.40f }, {  -0.35f,   0.45f },
    {  -0.15f,  -0.70f }, {   1.70f,  -0.80f }, {   0.50f,  -0.35f },
    {   1.60f,  -1.40f }, {   1.70f,  -1.15f }, {   0.40f,   0.05f },
    {  -0.70f,  -0.35f }, {  -0.70f,   0.15f }, {   0.00f,  -0.90f },
    {   0.05f,  -1.60f }, {   0.80f,   0.00f }, {   0.45f,  -0.80f },
    {   0.15f,  -1.30f }, {  -0.30f,   0.90f }, {   0.15f,   0.35f },
    {   0.25f,  -1.00f }, {   0.70f,   0.45f }, {  -0.25f,  -0.45f },
    {   0.00f,  -0.55f }, {   0.15f,  -0.05f }, {  -0.15f,   0.40f },
    {   0.30f,  -0.10f }, {   0.10f,  -0.25f }, {  -0.05f,   0.80f },
    {   0.25f,  -0.70f }, {   1.80f,  -1.35f }, {   0.95f,   0.40f },
    {   0.55f,   1.45f }, {  -0.10f,   0.55f }, {  -0.55f,  -0.60f },
    {  -0.20f,   0.70f }, {   0.40f,  -0.95f }, {   0.20f,  -1.45f },
    {   0.20f,  -0.40f }, {   0.15f,  -0.55f }, {   0.20f,   0.15f },
    {  -1.65f,   1.05f }, {   1.70f,   1.10f }, {  -0.70f,  -0.05f },
    {  -0.45f,  -0.20f }, {  -0.50f,  -0.35f }, {   0.35f,  -1.70f },
    {  -1.80f,   1.30f }, {   0.65f,  -0.05f }, {   0.40f,  -1.45f },
    {  -0.15f,  -1.00f }, {   1.50f,  -1.55f }, {  -0.55f,   0.60f },
    {   0.35f,  -0.55f }, {  -0.45f,   0.80f }, {   0.45f,   1.20f },
    {   0.35f,   0.95f }, {  -1.60f,   1.20f }, {   0.10f,  -0.70f },
    {   0.50f,   1.75f }, {   1.60f,   0.90f }, {  -0.10f,  -0.15f },
    {   0.30f,   0.80f }, {   0.50f,   0.70f }, {   0.40f,   0.30f },
    {   0.10f,   0.50f }, {  -0.15f,  -0.85f }, {   1.50f,  -0.75f },
    {   0.80f,   0.20f }, {   0.20f,   1.00f }, {   1.50f,  -0.45f },
    {   1.75f,  -1.00f },
};

// Small cylinder obstacle: radius 0.15 m, height 0.6 m.
// Spawned at a random position each episode via gz-transport.
static const char * OBS_CYLINDER_SDF = R"(
<?xml version='1.0'?>
<sdf version='1.8'>
  <model name='%NAME%'>
    <static>true</static>
    <link name='link'>
      <pose>0 0 0.3 0 0 0</pose>
      <collision name='col'>
        <geometry><cylinder><radius>0.15</radius><length>0.6</length></cylinder></geometry>
      </collision>
      <visual name='vis'>
        <geometry><cylinder><radius>0.15</radius><length>0.6</length></cylinder></geometry>
        <material><ambient>0.4 0.2 0.1 1</ambient><diffuse>0.4 0.2 0.1 1</diffuse></material>
      </visual>
    </link>
  </model>
</sdf>)";

// Minimal SDF 1.8 sphere — spawned each episode as the goal marker.
static const char * GOAL_SPHERE_SDF = R"(
<?xml version='1.0'?>
<sdf version='1.8'>
  <model name='goal_marker'>
    <static>true</static>
    <link name='link'>
      <visual name='visual'>
        <geometry><sphere><radius>%RADIUS%</radius></sphere></geometry>
        <material>
          <ambient>1 0 0 1</ambient>
          <diffuse>1 0 0 1</diffuse>
          <emissive>0.5 0 0 1</emissive>
        </material>
      </visual>
    </link>
  </model>
</sdf>)";

class ResetNode : public rclcpp::Node
{
public:
  ResetNode()
  : Node("reset_node"), rng_(std::random_device{}()), goal_spawned_(false), obs_spawned_(false)
  {
    tb3_model_     = declare_parameter("tb3_model", std::string("waffle_pi"));
    x_min_         = declare_parameter("world_x_min", -2.0);
    x_max_         = declare_parameter("world_x_max",  2.0);
    y_min_         = declare_parameter("world_y_min", -2.0);
    y_max_         = declare_parameter("world_y_max",  2.0);
    min_dist_      = declare_parameter("robot_min_goal_dist", 0.5);
    sphere_radius_ = declare_parameter("goal_sphere_radius",  0.1);
    world_name_    = declare_parameter("world_name", std::string("empty"));
    n_obstacles_   = declare_parameter("n_obstacles", 0);

    // Fixed robot spawn each episode, random goal only.
    // Default spawn: robot at (-0.7, 0), facing +x (matches stage 4-5 SDFs).
    // Set fixed_spawn:=false to revert to random robot spawn.
    fixed_spawn_   = declare_parameter("fixed_spawn",  true);
    spawn_x_       = declare_parameter("spawn_x",     -0.7);
    spawn_y_       = declare_parameter("spawn_y",      0.0);
    spawn_theta_   = declare_parameter("spawn_theta",  0.0);

    // Goal-validity parameters:
    //   arena_length = 4.2 → arena bounds ±2.1
    //   no-goal-spawn margin = 0.3 inflates each inner-wall rectangle.
    arena_length_  = declare_parameter("arena_length", 4.2);
    arena_width_   = declare_parameter("arena_width",  4.2);
    stage_num_     = declare_parameter("stage",        1);
    build_obstacle_rectangles(stage_num_);

    // Reentrant group so the odom callback can fire while the service
    // handler is sleeping after a teleport.
    auto reentrant_group = create_callback_group(
      rclcpp::CallbackGroupType::Reentrant);
    auto sub_opts = rclcpp::SubscriptionOptions();
    sub_opts.callback_group = reentrant_group;

    odom_sub_ = create_subscription<nav_msgs::msg::Odometry>(
      "/odom", 10,
      [this](nav_msgs::msg::Odometry::ConstSharedPtr msg) {
        std::lock_guard<std::mutex> lk(mtx_);
        odom_x_ = static_cast<float>(msg->pose.pose.position.x);
        odom_y_ = static_cast<float>(msg->pose.pose.position.y);
        auto & q = msg->pose.pose.orientation;
        odom_yaw_ = std::atan2(
          2.0f * (static_cast<float>(q.w) * static_cast<float>(q.z) +
                  static_cast<float>(q.x) * static_cast<float>(q.y)),
          1.0f - 2.0f * (static_cast<float>(q.y) * static_cast<float>(q.y) +
                         static_cast<float>(q.z) * static_cast<float>(q.z)));
      }, sub_opts);

    goal_pub_    = create_publisher<geometry_msgs::msg::PoseStamped>("/goal_pose", 10);
    marker_pub_  = create_publisher<visualization_msgs::msg::Marker>("/goal_marker", 10);
    cmd_vel_pub_ = create_publisher<geometry_msgs::msg::Twist>("/cmd_vel", 10);

    reset_srv_ = create_service<ResetEpisode>(
      "/reset_episode",
      [this](ResetEpisode::Request::ConstSharedPtr req,
             ResetEpisode::Response::SharedPtr     res) {
        handle_reset(req, res);
      });

    // Delete any leftover goal_marker from a previous run
    delete_entity("goal_marker");

    RCLCPP_INFO(get_logger(),
                "ResetNode ready. model=%s world=%s stage=%d "
                "arena=%.1fx%.1f spawn=(%.2f,%.2f,%.2f) fixed=%d "
                "inner_wall_rects=%zu",
                tb3_model_.c_str(), world_name_.c_str(), stage_num_,
                arena_length_, arena_width_,
                spawn_x_, spawn_y_, spawn_theta_, fixed_spawn_ ? 1 : 0,
                obstacle_rectangles_.size());
  }

private:
  void handle_reset(ResetEpisode::Request::ConstSharedPtr req,
                    ResetEpisode::Response::SharedPtr     res)
  {
    RCLCPP_INFO(get_logger(), "handle_reset: spawn_only=%d random_pose=%d radius=%.2f",
                req->spawn_only, req->random_pose, req->goal_radius);

    // ── Successive-goals path: spawn new goal only, don't teleport robot ──
    if (req->spawn_only) {
      // env_bridge now tracks robot in WORLD frame (via Ignition's pose feed),
      // so we use the same /odom subscriber's most-recent reading as a proxy
      // for robot world position. After full reset this is stable enough;
      // future refactor could subscribe to Ignition pose here too.
      float robot_wx, robot_wy;
      {
        std::lock_guard<std::mutex> lk(mtx_);
        robot_wx = odom_x_;
        robot_wy = odom_y_;
      }
      // Sample new goal in WORLD frame around robot's current world position.
      float ngx, ngy;
      sample_goal_near(robot_wx, robot_wy, req->goal_radius, ngx, ngy);

      // Publish /goal_pose in WORLD frame (no transform needed — env_bridge
      // now also tracks the robot in world frame).
      publish_goal(ngx, ngy);
      std::thread([this, ngx, ngy]() {
        update_goal_marker(ngx, ngy);
      }).detach();

      res->success = true;
      res->info    = "spawn_only_ok";
      RCLCPP_INFO(get_logger(),
                  "Spawn-only goal world=(%.2f,%.2f) r=%.2f robot_world=(%.2f,%.2f)",
                  ngx, ngy, req->goal_radius, robot_wx, robot_wy);
      return;
    }

    float rx, ry, rtheta, gx, gy;
    std::vector<XY>    obs_pos;
    std::vector<float> obs_yaw;

    if (req->random_pose) {
      sample_all_poses(rx, ry, rtheta, gx, gy, obs_pos, obs_yaw);
    } else {
      rx     = req->spawn_x;
      ry     = req->spawn_y;
      rtheta = req->spawn_theta;
      gx     = req->goal_x;
      gy     = req->goal_y;
    }

    {
      geometry_msgs::msg::Twist zero;
      cmd_vel_pub_->publish(zero);
    }
    std::this_thread::sleep_for(std::chrono::milliseconds(80));

    if (!obs_spawned_) {
      spawn_all_obstacles(obs_pos, obs_yaw);
    } else {
      teleport_all_obstacles(obs_pos, obs_yaw);
    }

    bool ok = teleport_robot(rx, ry, rtheta);

    // Wait for physics to settle and for odom to reflect the post-teleport state.
    // With MultiThreadedExecutor the odom callback fires during this sleep, so
    // odom_x_/odom_y_ will hold the fresh value — whether or not the DiffDrive
    // plugin resets its accumulated pose on set_pose (Ignition Fortress behaviour
    // can vary). The robot is stationary (zero cmd_vel above), so there is no
    // movement contaminating the reading.
    std::this_thread::sleep_for(std::chrono::milliseconds(300));

    float post_odom_x, post_odom_y, post_odom_yaw;
    {
      std::lock_guard<std::mutex> lk(mtx_);
      post_odom_x   = odom_x_;
      post_odom_y   = odom_y_;
      post_odom_yaw = odom_yaw_;
    }

    // env_bridge now tracks robot in WORLD frame via Ignition's pose feed,
    // so /goal_pose is published in WORLD frame directly. No odom transform.
    (void)post_odom_yaw;  // silence unused-var warning
    publish_goal(gx, gy);
    std::thread([this, gx, gy]() { update_goal_marker(gx, gy); }).detach();

    res->success = ok;
    res->info    = ok ? "reset_ok" : "teleport_failed";

    RCLCPP_INFO(get_logger(),
                "Reset: robot_world=(%.2f,%.2f,θ=%.2f) goal_world=(%.2f,%.2f) "
                "post_odom=(%.2f,%.2f)",
                rx, ry, rtheta, gx, gy, post_odom_x, post_odom_y);
  }

  // ── pose sampling ──────────────────────────────────────────────────────────
  using XY = std::pair<float, float>;
  static std::string obs_name(int i) { return "dyn_obs_" + std::to_string(i); }

  // Sample a goal at a noisy radius around (rx, ry):
  //   ring_position = U(0, 1)
  //   origin = radius + N(0, 0.1)
  //   goal = robot + (cos(2*pi*ring_position), sin(2*pi*ring_position)) * origin
  //   retry up to 100 times if not in arena bounds.
  // Noise is RE-SAMPLED on every retry so a bad radius noise doesn't lock
  // out all 100 attempts.
  void sample_goal_near(float rx, float ry, float radius,
                        float & gx, float & gy)
  {
    std::uniform_real_distribution<float> dring(0.0f, 1.0f);
    std::normal_distribution<float>       dnoise(0.0f, 0.1f);
    for (int tries = 0; tries < 100; ++tries) {
      float ring_position = dring(rng_);
      float origin = std::max(radius + dnoise(rng_), 0.1f);
      float th = 2.0f * static_cast<float>(M_PI) * ring_position;
      gx = rx + origin * std::cos(th);
      gy = ry + origin * std::sin(th);
      if (goal_is_in_arena(gx, gy)) return;
    }
    // After 100 failures, clamp into bounds (we don't do a full sim reset
    // here — that would discard the policy's mid-episode momentum, which
    // is the whole point of successive goals).
    gx = std::clamp(gx,
                    static_cast<float>(x_min_) + 0.3f,
                    static_cast<float>(x_max_) - 0.3f);
    gy = std::clamp(gy,
                    static_cast<float>(y_min_) + 0.3f,
                    static_cast<float>(y_max_) - 0.3f);
  }

  // Goal validity check — arena bounds AND every inner-wall rectangle
  // (inflated by the no-goal-spawn margin = 0.3).
  bool goal_is_in_arena(float gx, float gy) const
  {
    // Arena bounds: arena_length / 2 = 2.1
    const float half_x = static_cast<float>(arena_length_) / 2.0f;
    const float half_y = static_cast<float>(arena_width_)  / 2.0f;
    if (gx >  half_x || gx < -half_x) return false;
    if (gy >  half_y || gy < -half_y) return false;
    // Inner-wall rectangles (only populated for stages with inner_walls)
    for (const auto & r : obstacle_rectangles_) {
      if (gx >= r.x_min && gx <= r.x_max &&
          gy >= r.y_min && gy <= r.y_max) {
        return false;
      }
    }
    return true;
  }

  // Build the obstacle rectangle list for goal_is_valid.
  // Each inner wall is 1 m × 0.15 m × 0.5 m, inflated by the no-goal-spawn
  // margin on every side. Goal-sampling rejects any pose inside one of
  // these rectangles, so goals never appear inside / on / behind a wall.
  // Stage 4 has the canonical 7-wall set in a 5x5 arena; stage 5 has its
  // own 8-wall layout in a 7x7 arena (generalisation probe).
  void build_obstacle_rectangles(int stage)
  {
    obstacle_rectangles_.clear();
    const bool has_inner_walls = (stage == 4 || stage == 5);
    if (!has_inner_walls) return;

    constexpr float MARGIN = 0.3f;          // no-goal-spawn margin
    constexpr float WALL_L = 1.0f;          // inner wall length
    constexpr float WALL_W = 0.15f;         // inner wall thickness
    struct WallSpec { float x, y, yaw; };

    // Stage 4 — canonical 7-wall layout, 5x5 arena.
    static const WallSpec walls_stage4[] = {
      { -2.0f, -1.5f,    0.0f      },
      { -0.5f, -2.0f,   -1.5708f   },
      {  1.0f, -1.0f,    1.5708f   },
      {  1.2f,  1.9f,   -1.5708f   },
      {  1.9f,  0.4f,    0.0f      },
      { -0.5f,  1.5f,    0.0f      },
      { -1.2f,  0.092f, -1.5708f   },
    };
    // Stage 5 — 8 walls inside the 7x7 arena. Must match
    // tb3_stage5.sdf and INNER_WALLS_STAGE5 in gen_maps.py.
    static const WallSpec walls_stage5[] = {
      { -1.5f,  2.0f,    0.0f      },
      {  1.5f,  2.0f,    0.0f      },
      { -2.0f,  0.5f,    1.5708f   },
      {  0.5f,  0.5f,    1.5708f   },
      {  0.0f, -1.5f,    1.5708f   },
      {  2.0f, -0.5f,    1.5708f   },
      { -1.5f, -2.5f,    0.0f      },
      {  1.5f, -2.5f,    0.0f      },
    };

    const WallSpec * walls;
    size_t n_walls;
    if (stage == 5) {
      walls = walls_stage5;
      n_walls = sizeof(walls_stage5) / sizeof(walls_stage5[0]);
    } else {
      walls = walls_stage4;
      n_walls = sizeof(walls_stage4) / sizeof(walls_stage4[0]);
    }

    for (size_t i = 0; i < n_walls; ++i) {
      const auto & w = walls[i];
      bool horizontal = std::abs(w.yaw) < 1e-3f;
      float sx = horizontal ? (WALL_L + 2 * MARGIN) : (WALL_W + 2 * MARGIN);
      float sy = horizontal ? (WALL_W + 2 * MARGIN) : (WALL_L + 2 * MARGIN);
      Rect r;
      r.x_min = w.x - sx * 0.5f;
      r.x_max = w.x + sx * 0.5f;
      r.y_min = w.y - sy * 0.5f;
      r.y_max = w.y + sy * 0.5f;
      obstacle_rectangles_.push_back(r);
    }
  }

  // Transform a point (ox, oy) in odom frame to world frame, using the
  // odom↔world relationship cached at the last full reset.
  // Derivation: at teleport, robot was at world (rx, ry, rtheta) and at
  // odom (post_odom_x, post_odom_y, post_odom_yaw). A vector that points
  // some direction in odom frame points the same physical direction in
  // world frame rotated by alpha = rtheta - post_odom_yaw.
  void odom_to_world(float ox, float oy, float & wx, float & wy) const
  {
    float alpha = reset_robot_world_yaw_ - reset_post_odom_yaw_;
    float ca = std::cos(alpha), sa = std::sin(alpha);
    float dox = ox - reset_post_odom_x_;
    float doy = oy - reset_post_odom_y_;
    wx = reset_robot_world_x_ + ca * dox - sa * doy;
    wy = reset_robot_world_y_ + sa * dox + ca * doy;
  }

  // Inverse of odom_to_world — used to convert a world-frame goal back to
  // odom so the RL stack (which sees /goal_pose in odom frame) navigates
  // toward the right physical location.
  void world_to_odom(float wx, float wy, float & ox, float & oy) const
  {
    float alpha = reset_robot_world_yaw_ - reset_post_odom_yaw_;
    float ca = std::cos(-alpha), sa = std::sin(-alpha);
    float dwx = wx - reset_robot_world_x_;
    float dwy = wy - reset_robot_world_y_;
    ox = reset_post_odom_x_ + ca * dwx - sa * dwy;
    oy = reset_post_odom_y_ + sa * dwx + ca * dwy;
  }

  // Random spawn + goal sampled from VALID_POSITIONS (pre-validated against
  // stages 1-5). Each pick is additionally cross-checked against the
  // current stage's obstacle_rectangles_ — needed for stage 5 which has a
  // different wall layout that some legacy entries fall inside of. Spawn
  // heading is uniform in [-π, π]. Spawn and goal must be at least 2.0 m
  // apart so the task is meaningful.
  void sample_all_poses(float & rx, float & ry, float & rtheta,
                        float & gx, float & gy,
                        std::vector<XY> & obs_pos, std::vector<float> & obs_yaw)
  {
    obs_pos.clear();
    obs_yaw.clear();

    std::uniform_int_distribution<int> didx(0, VALID_POSITIONS.size() - 1);
    std::uniform_real_distribution<float> dtheta(-M_PI, M_PI);

    // Pick spawn — retry until it passes the current stage's wall check.
    rx = ry = 0.0f;
    for (int tries = 0; tries < 200; ++tries) {
      auto spawn = VALID_POSITIONS[didx(rng_)];
      if (goal_is_in_arena(spawn.first, spawn.second)) {
        rx = spawn.first;
        ry = spawn.second;
        break;
      }
    }
    rtheta = dtheta(rng_);

    // Pick goal — far enough from spawn AND clear of walls.
    gx = gy = 0.0f;
    for (int tries = 0; tries < 200; ++tries) {
      auto g = VALID_POSITIONS[didx(rng_)];
      if (!goal_is_in_arena(g.first, g.second)) continue;
      float dx = g.first - rx;
      float dy = g.second - ry;
      if (std::sqrt(dx * dx + dy * dy) >= 2.0f) {
        gx = g.first;
        gy = g.second;
        break;
      }
    }
    prev_goal_x_ = gx;
    prev_goal_y_ = gy;
  }

  void spawn_all_obstacles(const std::vector<XY> & poses,
                           const std::vector<float> & yaws)
  {
    for (int i = 0; i < static_cast<int>(poses.size()); ++i) {
      std::string sdf(OBS_CYLINDER_SDF);
      auto p = sdf.find("%NAME%");
      if (p != std::string::npos) sdf.replace(p, 6, obs_name(i));
      bool ok = spawn_entity(sdf, poses[i].first, poses[i].second, 0.0f, yaws[i]);
      RCLCPP_INFO(get_logger(), "Spawn %s at (%.2f,%.2f) yaw=%.2f: %s",
                  obs_name(i).c_str(), poses[i].first, poses[i].second,
                  yaws[i], ok ? "OK" : "FAILED");
    }
    obs_spawned_ = true;
  }

  void teleport_all_obstacles(const std::vector<XY> & poses,
                              const std::vector<float> & yaws)
  {
    for (int i = 0; i < static_cast<int>(poses.size()); ++i)
      teleport_entity(obs_name(i), poses[i].first, poses[i].second, yaws[i], 0.0f);
  }

  // ── Ignition gz-transport: teleport any entity ────────────────────────────
  bool teleport_entity(const std::string & name, float x, float y,
                       float theta = 0.0f, float z = 0.0f)
  {
    ignition::msgs::Pose req;
    req.set_name(name);
    req.mutable_position()->set_x(x);
    req.mutable_position()->set_y(y);
    req.mutable_position()->set_z(z);
    req.mutable_orientation()->set_x(0.0);
    req.mutable_orientation()->set_y(0.0);
    req.mutable_orientation()->set_z(std::sin(theta * 0.5));
    req.mutable_orientation()->set_w(std::cos(theta * 0.5));
    ignition::msgs::Boolean res; bool result = false;
    ign_node_.Request("/world/" + world_name_ + "/set_pose", req, 2000, res, result);
    return result;
  }

  // ── Ignition gz-transport: teleport robot ──────────────────────────────────
  bool teleport_robot(float x, float y, float theta)
  {
    ignition::msgs::Pose req;
    req.set_name(tb3_model_);
    req.mutable_position()->set_x(x);
    req.mutable_position()->set_y(y);
    req.mutable_position()->set_z(0.0);
    req.mutable_orientation()->set_x(0.0);
    req.mutable_orientation()->set_y(0.0);
    req.mutable_orientation()->set_z(std::sin(theta * 0.5));
    req.mutable_orientation()->set_w(std::cos(theta * 0.5));

    ignition::msgs::Boolean res;
    bool result = false;
    std::string service = "/world/" + world_name_ + "/set_pose";

    bool executed = ign_node_.Request(service, req, 2000, res, result);
    if (!executed || !result) {
      RCLCPP_WARN(get_logger(), "set_pose failed for %s (executed=%d result=%d)",
                  tb3_model_.c_str(), executed, result);
      return false;
    }
    return true;
  }

  // ── Ignition gz-transport: spawn entity ───────────────────────────────────
  bool spawn_entity(const std::string & sdf_str, float x, float y, float z,
                    float yaw = 0.0f)
  {
    ignition::msgs::EntityFactory req;
    req.set_sdf(sdf_str);
    req.mutable_pose()->mutable_position()->set_x(x);
    req.mutable_pose()->mutable_position()->set_y(y);
    req.mutable_pose()->mutable_position()->set_z(z);
    req.mutable_pose()->mutable_orientation()->set_z(std::sin(yaw * 0.5f));
    req.mutable_pose()->mutable_orientation()->set_w(std::cos(yaw * 0.5f));

    std::string service = "/world/" + world_name_ + "/create";

    for (int attempt = 1; attempt <= 3; ++attempt) {
      ignition::msgs::Boolean res;
      bool result = false;
      bool executed = ign_node_.Request(service, req, 3000, res, result);
      if (executed && result) return true;
      RCLCPP_WARN(get_logger(), "spawn_entity attempt %d/3 failed (executed=%d result=%d)",
                  attempt, executed, result);
      std::this_thread::sleep_for(std::chrono::milliseconds(200));
    }
    return false;
  }

  // ── Ignition gz-transport: delete entity ──────────────────────────────────
  void delete_entity(const std::string & name)
  {
    ignition::msgs::Entity req;
    req.set_name(name);
    req.set_type(ignition::msgs::Entity::MODEL);

    ignition::msgs::Boolean res;
    bool result = false;
    std::string service = "/world/" + world_name_ + "/remove";

    ign_node_.Request(service, req, 2000, res, result);
  }

  // ── goal marker management ─────────────────────────────────────────────────
  void update_goal_marker(float gx, float gy)
  {
    // If the marker already exists, just teleport it to the new position
    // (avoids "Visual: [goal_marker] already exists" GUI errors from
    // delete-then-respawn race with fast successive goal events).
    if (goal_spawned_) {
      teleport_entity("goal_marker", gx, gy, 0.0f, static_cast<float>(sphere_radius_));
    } else {
      std::string sdf(GOAL_SPHERE_SDF);
      auto pos = sdf.find("%RADIUS%");
      if (pos != std::string::npos)
        sdf.replace(pos, 8, std::to_string(sphere_radius_));
      if (spawn_entity(sdf, gx, gy, static_cast<float>(sphere_radius_)))
        goal_spawned_ = true;
    }

    // RViz marker
    visualization_msgs::msg::Marker m;
    m.header.frame_id = "map";
    m.header.stamp    = now();
    m.ns = "goal"; m.id = 0;
    m.type   = visualization_msgs::msg::Marker::SPHERE;
    m.action = visualization_msgs::msg::Marker::ADD;
    m.pose.position.x = gx;
    m.pose.position.y = gy;
    m.pose.position.z = sphere_radius_;
    m.pose.orientation.w = 1.0;
    m.scale.x = m.scale.y = m.scale.z = sphere_radius_ * 2.0;
    m.color.r = 1.0f; m.color.g = 0.0f; m.color.b = 0.0f; m.color.a = 1.0f;
    marker_pub_->publish(m);
  }

  void publish_goal(float gx, float gy)
  {
    geometry_msgs::msg::PoseStamped ps;
    ps.header.frame_id = "odom";
    ps.header.stamp    = now();
    ps.pose.position.x = gx;
    ps.pose.position.y = gy;
    ps.pose.orientation.w = 1.0;
    goal_pub_->publish(ps);
  }

  // ── members ────────────────────────────────────────────────────────────────
  struct Rect { float x_min, x_max, y_min, y_max; };

  std::mutex mtx_;
  std::string tb3_model_, world_name_;
  double x_min_, x_max_, y_min_, y_max_;
  double min_dist_, sphere_radius_;
  bool   fixed_spawn_;
  double spawn_x_, spawn_y_, spawn_theta_;
  // Goal validity parameters
  double arena_length_, arena_width_;
  int    stage_num_;
  std::vector<Rect> obstacle_rectangles_;

  // Last goal published this episode — used for Manhattan-distance
  // constraint on the NEXT goal (ensures consecutive goals are diverse).
  float prev_goal_x_ = 0.0f;
  float prev_goal_y_ = 0.0f;
  float odom_x_ = 0.0f, odom_y_ = 0.0f, odom_yaw_ = 0.0f;

  // Full odom↔world transform captured at the start of each episode (full reset).
  // Without this, goals sampled in odom frame can fall outside the world arena
  // when DiffDrive's odom origin or heading drifts from world.
  float reset_robot_world_x_  = 0.0f;
  float reset_robot_world_y_  = 0.0f;
  float reset_robot_world_yaw_= 0.0f;
  float reset_post_odom_x_    = 0.0f;
  float reset_post_odom_y_    = 0.0f;
  float reset_post_odom_yaw_  = 0.0f;

  int    n_obstacles_;
  std::mt19937 rng_;
  bool goal_spawned_;
  bool obs_spawned_;
  std::vector<std::pair<float,float>> obs_xy_;

  ignition::transport::Node ign_node_;

  rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr        odom_sub_;
  rclcpp::Publisher<geometry_msgs::msg::PoseStamped>::SharedPtr   goal_pub_;
  rclcpp::Publisher<visualization_msgs::msg::Marker>::SharedPtr   marker_pub_;
  rclcpp::Publisher<geometry_msgs::msg::Twist>::SharedPtr         cmd_vel_pub_;
  rclcpp::Service<ResetEpisode>::SharedPtr                        reset_srv_;
};

int main(int argc, char * argv[])
{
  rclcpp::init(argc, argv);
  auto node = std::make_shared<ResetNode>();
  rclcpp::executors::MultiThreadedExecutor executor;
  executor.add_node(node);
  executor.spin();
  rclcpp::shutdown();
  return 0;
}
