#!/usr/bin/env python3
"""Generate a list of safe (x, y) positions for random spawn/goal sampling.

A position is "safe" if it:
  - lies inside the 5x5 arena with a 0.6 m margin from the outer walls
  - is at least 0.4 m from every inner-wall rectangle
  - is at least 0.55 m from every static cylinder centre (cylinder r = 0.15 m)
  - is at least 0.5 m from every moving-cylinder base position
    (these bases vary per stage; the union over all stages is used here)

The output is a C++-ready vector initializer, paste it into reset_node.cpp.
"""

from __future__ import annotations

import argparse
import math
import random
from dataclasses import dataclass


# ── arena ─────────────────────────────────────────────────────────────────────
ARENA_HALF = 1.8       # half-side of usable area (outer walls are at ±2.425)

# ── inner walls (7 segments, 1 m × 0.15 m, see gen_stages.py) ─────────────────
# (cx, cy, yaw) of each segment, all length 1 m, thickness 0.15 m.
INNER_WALLS = [
    (-2.0, -1.5,  0.0),
    (-0.5, -2.0, -math.pi / 2),
    ( 1.0, -1.0,  math.pi / 2),
    ( 1.2,  1.9, -math.pi / 2),
    ( 1.9,  0.4,  0.0),
    (-0.5,  1.5,  0.0),
    (-1.2,  0.092, -math.pi / 2),
]
WALL_LEN  = 1.0
WALL_W    = 0.15
WALL_MARGIN = 0.40     # clearance from any wall edge

# ── static cylinders (stages 2, 3) ────────────────────────────────────────────
STATIC_CYLS = [(-1.0, -1.0), (-1.0, 1.0), (1.0, -1.0), (1.0, 1.0)]
CYL_RADIUS  = 0.15
CYL_MARGIN  = 0.40     # clearance beyond cylinder edge

# ── moving-cylinder base positions (union across stages 4-10) ─────────────────
MOVING_BASES = [( 2.0,  2.0), (-2.0, -2.0), ( 2.0, -2.0),
                (-2.0,  2.0), (-2.0,  0.0), ( 2.0,  0.0)]
MOVING_RADIUS = 0.16
MOVING_MARGIN = 0.50   # cylinders move — give extra margin near their bases


@dataclass
class Rect:
    cx: float
    cy: float
    half_x: float       # in wall-local frame (along the 1-m length axis)
    half_y: float       # in wall-local frame (along the 0.15-m thickness)
    cos_yaw: float
    sin_yaw: float

    def contains(self, x: float, y: float, margin: float) -> bool:
        """True if (x, y) lies inside the rectangle inflated by `margin`."""
        # rotate (x, y) into the wall's local frame
        dx = x - self.cx
        dy = y - self.cy
        lx =  self.cos_yaw * dx + self.sin_yaw * dy
        ly = -self.sin_yaw * dx + self.cos_yaw * dy
        return (abs(lx) <= self.half_x + margin and
                abs(ly) <= self.half_y + margin)


def build_wall_rects() -> list[Rect]:
    rects: list[Rect] = []
    for cx, cy, yaw in INNER_WALLS:
        rects.append(Rect(
            cx=cx, cy=cy,
            half_x=WALL_LEN / 2,
            half_y=WALL_W   / 2,
            cos_yaw=math.cos(yaw),
            sin_yaw=math.sin(yaw),
        ))
    return rects


def is_safe(x: float, y: float, walls: list[Rect]) -> bool:
    if abs(x) > ARENA_HALF or abs(y) > ARENA_HALF:
        return False
    for w in walls:
        if w.contains(x, y, WALL_MARGIN):
            return False
    for (cx, cy) in STATIC_CYLS:
        if math.hypot(x - cx, y - cy) < CYL_RADIUS + CYL_MARGIN:
            return False
    for (bx, by) in MOVING_BASES:
        if math.hypot(x - bx, y - by) < MOVING_RADIUS + MOVING_MARGIN:
            return False
    return True


def generate(n_positions: int, seed: int = 42,
             min_pair_separation: float = 0.5) -> list[tuple[float, float]]:
    """Sample `n_positions` safe (x, y) points on a 0.05 m grid.

    Points are spaced at least `min_pair_separation` apart from each other
    so the list isn't dominated by clusters in any one corner.
    """
    rng = random.Random(seed)
    walls = build_wall_rects()
    out: list[tuple[float, float]] = []
    attempts = 0
    while len(out) < n_positions and attempts < 100_000:
        attempts += 1
        # snap to 0.05 m grid for tidier numbers
        x = round(rng.uniform(-ARENA_HALF, ARENA_HALF) * 20) / 20
        y = round(rng.uniform(-ARENA_HALF, ARENA_HALF) * 20) / 20
        if not is_safe(x, y, walls):
            continue
        # min spacing
        if any(math.hypot(x - px, y - py) < min_pair_separation
               for (px, py) in out):
            continue
        out.append((x, y))
    return out


def emit_cpp(positions: list[tuple[float, float]]) -> str:
    lines = []
    lines.append("// Auto-generated by tools/gen_positions.py.")
    lines.append(f"// {len(positions)} positions, all safe across stages 1-10.")
    lines.append("static const std::vector<std::pair<float, float>> "
                 "VALID_POSITIONS = {")
    for (x, y) in positions:
        lines.append(f"    {{ {x:>6.2f}f, {y:>6.2f}f }},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("-n", "--n-positions", type=int, default=100)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--min-sep", type=float, default=0.15,
                   help="minimum separation between positions in the list (m)")
    args = p.parse_args()

    positions = generate(args.n_positions, args.seed, args.min_sep)
    print(emit_cpp(positions))
    print(f"// generated {len(positions)} positions", flush=True)


if __name__ == "__main__":
    main()
